export const runtime = "nodejs";

/**
 * Serves the Firebase Messaging service worker (Part 8.4).
 *
 * A ROUTE rather than a static file in public/, so the Firebase config comes from
 * the same environment variables as the rest of the app. A service worker cannot
 * read process.env at runtime, so the usual approach is to paste the config into a
 * static file, which then silently drifts the first time a value changes. All of
 * these are NEXT_PUBLIC_ values that already ship in the client bundle, so nothing
 * secret is being exposed by templating them here.
 *
 * The path matters: firebase/messaging looks for /firebase-messaging-sw.js at the
 * root scope by default, and a worker served from a subpath cannot claim the root.
 */
export async function GET() {
  const config = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  };

  // The compat build is what runs inside a service worker: the modular SDK assumes
  // a bundler, and importScripts has no module resolution.
  const body = `/* Generated by app/firebase-messaging-sw.js/route.ts. Do not edit by hand. */
importScripts("https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/10.14.1/firebase-messaging-compat.js");

firebase.initializeApp(${JSON.stringify(config)});

const messaging = firebase.messaging();

// Fired only when the page is not in the foreground. Foreground messages are
// handled by onMessage in the app itself, which shows a toast instead: a system
// notification for a tab the user is already looking at is just noise.
messaging.onBackgroundMessage((payload) => {
  const data = payload.data || {};
  const notification = payload.notification || {};

  const options = {
    body: notification.body || "",
    icon: "/icon-192.png",
    data: { url: "/competitors", videoUrl: data.url || "" },
  };
  // Assigned only when present. Setting the key to a missing value is legal JS but
  // prints that keyword into this generated file, which would defeat the build
  // check that scans it for exactly that word to catch config that failed to
  // template in.
  if (data.channelId) options.tag = "breakout-" + data.channelId;

  self.registration.showNotification(notification.title || "Viewly", options);
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const target = (event.notification.data && event.notification.data.url) || "/competitors";

  // Focus an existing Viewly tab rather than opening a duplicate every time.
  event.waitUntil(
    clients.matchAll({ type: "window", includeUncontrolled: true }).then((all) => {
      for (const client of all) {
        if (client.url.includes(target) && "focus" in client) return client.focus();
      }
      return clients.openWindow(target);
    }),
  );
});
`;

  return new Response(body, {
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      // Lets the worker control the whole origin, not just its own directory.
      "Service-Worker-Allowed": "/",
      // Short cache: this is generated, and a stale worker is hard to dislodge.
      "Cache-Control": "public, max-age=0, must-revalidate",
    },
  });
}
